tomasklaen/uosc

uosc.lua

I think this makes it easier to toggle UOSC on and off. Perhaps for full Interoperability with other OSC's this should also require `uosc=yes` =]

Bail if original osc is enabled

---

uosc.lua

There is apparently no way to get the current position, so disabling the bar like the script currently does for images.

Fix crash when using --image-display-duration

---

README.md
uosc.conf
uosc.lua

Chapter naming has changed to accommodate for categories.
This is the bare minimum to support new & old versions if you don't want all the new categories:
`chapter_ranges=^op| op$|opening<968638:0.5>.*, ^ed| ed$|^end|ending$<968638:0.5>.*|{eof}, sponsor start<3535a5:.5>sponsor end, segment start<3535a5:0.5>segment end`

Support for sponsorblock categories

---

uosc.lua

Fix: accept all whitespace characters during input.conf parsing

---

uosc.lua

Title.
When not watching a local video I still want to load locally downloaded subtitles.
This just makes the load menu default to $HOME when the video path is a protocol.

Made subtitle loading possible when watching remote videos

---

uosc.conf
uosc.lua

I added an optional button where uosc's menu appears, so as to have the menu be consistent with the other UI components being mouse-accessible by proximity alone.
Personally, I have as old habit to use mpv's defaults of `mbtn_right cycle pause` and `mbtn_left ignore`, leaving it like that since not all my keyboards have a menu key, so the switch to uosc's suggested example has been awkward. Initially, I wrote this as a separate script to call `script-binding uosc/menu` when clicked in roughly the same area, but I liked it so much that I felt a visual indicator was worth making, and that also let the clickable area be smaller.

Add menu button widget

---

README.md
uosc.lua

Thanks for this awesome mpv script. Here are some very small improvement suggestions:
[keep playlist on delete-file-next command](https://github.com/darsain/uosc/commit/0005120302085f518e11d14e68d06e6f0d038e38):
This is actually a bug fix. Before when using the delete-file-next binding in a playlist, it would just skip to the next file in the folder and disregard the playlist. Now it moves to the next file in the playlist as it is described in the readme.
[add flash-top-bar command](https://github.com/darsain/uosc/commit/f237f70bcefa8bf7251f2202b8947703596e4092):
Adds another flash binding, just like the other ones. I found it very helpful to flash the top bar when using a "next" shortcut, to see the file title.
[Also allow '#menu:' as keyword instead of '#!' in …

Fix delete-file-next; add flash-top-bar command; allow '#menu:' as keyword

---

uosc.lua

The updated state of the cache was not visible when the player was
paused and not interacted with.
Now a render is requested on every cache update, which happens roughly
two times per second for me.
Due to my slow internet connection I often have a video buffering on one monitor while I'm doing something on the other one. Having to mouse over to see how far it has buffered was annoying.

Render on cache updates

---

uosc.lua

I think there is slightly less jitter with `display-fps` then with `estimated-display-fps`, although it's really hard to tell and I don't have multiple monitors with different refresh rates to test with.
Simply swap them around if you want to try it yourself.
I've also noticed that `estimated-display-fps` does not get updated when the video is paused, so when there was a low estimated fps because of e.g. heavy background activity, then the refresh rate during pause will also be low. This could be worked around by adding `state.pause and` in front of it.

Automatically choose rendering frequency

---

uosc.lua

When starting the player paused, the static pause indicator was not shown.
By ignoring the initial invocation only for the flash indicator, this is now fixed.

Fix initial static pause indicator

---

uosc.lua

Due to the 100 leeway, a chapter starting at 00:00 would not be active,
when the playback time also was 00:00.

Remove 100ms leeway in chapter menu

---

uosc.lua

When the menu was initialized without items and then the items and
active item were set afterwards (like is the case with playlist),
then the initialization of the selection and scroll position would
not work.
`on_display_change()` has to happen before scrolling, because it updates the `scroll_height` and `scroll_to()` caps on that.

Fix menu selection initialization and scroll position

---

uosc.lua

When dragging the speed dial and letting go over the timeline,
`this:fadeout` was called, but that function does not exist.
Introduced in 755194352f6eacb3488fd519be6ecbc21137463d
I think this was simply forgotten in the aforementioned commit.
Closes #78

Fix speed dial crash

---

uosc.lua

Pausing a live stream leads to the remaining time changing without any actual playback, but so far the UI would only update the remaining time when the playback time changed.

Update and render on remaining time changes

---

uosc.lua

Use the actual font size of hints to estimate their width.
`item_content_spacing` is not needed in the calculation of `hint_width`,
because it is already considered in the calculation of `title_clip_x`,
otherwise we'll end up with twice the spacing.

Fix hint width estimation

---

uosc.lua

Opening and closing a submenu very quickly very quickly (smashing right and left arrow as fast as I possibly can) resulted in a nil error.
The error occurred in line 1103 and after adding a nil check it would result in a nil error in line 1071 instead, so I added a nil check there as well.
While testing I also managed to end up with an unresponsive menu two times. Closing and reopening fixes the problem, so much less problematic then the interface crashing. It's also really hard to reproduce. I don't know if that problem was introduced by my changes here or if it already existed before and I would just end up with a nil crash before that ever happened.
It's not a nice solution, but I couldn't find the root cause of the problem (at least not without spending hours searching for it).

Fix menu crash when quickly repeatedly opening and closing submenu

---

uosc.conf
uosc.lua

Uses a new option `ui_scale` for scaling the UI as well as the `display-hidpi-scale` property.
Has been inspired by the scaling in [console.lua](https://github.com/mpv-player/mpv/blob/0044c19f0de29ff752eb708365322b0ec16b53e7/player/lua/console.lua#L132-L138). 
Console observes the `display-hidpi-scale` property and renders whenever it changes, however this results in an error in line 1453 `attempt to index upvalue 'forced_key_bindings' (a nil value)`. That's why I commented it out. It's already way too late, so I'm not gonna look into that now. If you know how to fix that, that would be great.
Fixes #81

Add UI scaling

---

uosc.lua

Shows volume bar when blank or view a still image feels weird and noisy, so hide it.

Show volume-bar only when audio is available

---

uosc.lua

Scrolling up to change a value is semantically associated with
increasing that value.
Volume already worked this way, and the same is true for seeking
by scrolling outside of the UI, but scrolling up on the timeline
seeked backwards and scrolling up on the speed widget reduced speed.
Now scrolling on the timeline or outside of the UI seeks in the same
direction and speed also increases when scrolling up on the widget.
The restriction of only allowing positive numbers for `timeline_step`
has also been lifted, allowing users to set negative numbers
if they want to reverse the scrolling direction of timeline seeking.
This was already possible for speed and volume.

Consistant scrolling direction

---

uosc.lua

5f31a248eed0fecca694fea879032d1179af0aee overwrote the direction change
from 35f058d760202bb30f932e98d6b6981c9c944a33. This corrects that.

Correct speed scrolling direction

---

uosc.lua

While I prefer the version with `goto`, I was recently made aware in one of me PRs for mpv that `goto` is not supported in lua 5.1. mpv supports lua 5.1 as minimum version, so user scripts should too.
Simply replaced the `goto` with a big if block.
While testing this I noticed that the notch at 100 sometimes shows and sometimes disappears depending on the position while dragging (and i confirmed it already did before my change). Must be some floating point thing.

Remove goto for lua 5.1 compatiblity

---

uosc.lua

Add chapter title to hovered time

---

uosc.lua

Menu offset would not get updated when the width changed, leading to things like this when entering/leaving fullscreen (or maximize):
(I set the min width to 100 for that screenshot so that the width actually changes when full screened)
Now it behaves correctly.
The dimensions of the menu now also only get updated when necessary.

Menu offset and dimensions update

---

uosc.conf
uosc.lua

I was wondering why the menu _appears_ wider when windowed then when in fullscreen.
Turns out they actually were the same width `menu_min_width`, but in windowed it felt too wide because of the change in font size and item height. I made the width configurable and introduced a new one for fullscreen that is roughly 1.4 times the size of the windowed width, because item height and font size also change by that factor when in fullscreen.
While trying out different minimum widths, one of the entries with a submenu got clipped by the submenu icon.
Turns out that icon was not considered during the width estimation.
Now people can make their menu as narrow as the text allows.
I personally prefer
```
menu_min_width=185
menu_min_width_fullscreen=260
```
but I left the default for windowed the way …

Menu width configuration

---

uosc.lua

See commit messages for what and why.
I was at first worried that rounding the chapter lines would result in some chapters having different widths, but that turned out to not be a problem with integer values for the width.

Timeline rounding

---

uosc.lua

Started crashing in line 1935 after updating to the latest code.
Turns out that depending on how the timing works out when starting, `playlist_count` might still be nil when rendering.
Simply initialize `playlist_count` and `playlist_pos` to make sure that doesn't happen.

Initialize `playlist_count` to prevent crash

---

uosc.lua

`foreground_size` used to be calculated based on the background
coordinates, now it reflects the actual foreground size.
Won't make much of a difference in practice, but it's technically more correct so we might as well.

Foreground size based on foreground coordinates

---

scripts/uosc.lua

The progress line started at an x of 0 instead of `bax`, resulting in no border at the left side and twice the border at the right side.

Add border x offset to progress line

---

scripts/uosc.lua

This didn't just show the wrong time when hovering, but also the wrong
chapter when close to a transition.

fix: hovered time uses correct time

---

scripts/uosc.lua

I don't know if that's a desirable change or not, but I was wondering why, when seeking to a position and having an odd number as line width, it would end up with blurry edges at the progress line. After all with an odd number there is exactly one pixel in the middle and so it should be able to cleanly display the progress line.
After ruling out faulty time calculation and rendering, it turns out the problem was that cursor x coordinate points at the left edge of the pixel, while what I visualizing was in the middle of the pixel.
Technically this also makes hovered chapters more accurate, because depending how the chapter line gets rounded, without this change it might still show the previous chapter even one pixel after the line.
Not that anyone would ever really notice that without …

Timeline cursor pixel middle

---

scripts/uosc.lua

The cursor line used to be one pixel further left when on foreground then when on background.
Now it keeps the same position relative to the cursor.

fix: cursor line has same position in foreground and background

---

scripts/uosc.lua

The local `menu` shadowed the global `menu`, thus accesing it's methods didn't work.

fix: nil error in `show-menu` api

---

scripts/uosc.lua

fix: remove unneeded closing curly brace from title

---

scripts/uosc.lua

With a step size of 1 it was possible to set volume to -1.
mpv permits setting volume to -1 for legacy reasons, so cap it in the ui.
There was a `set_from_cursor` method for setting volume in the speed element.
Probably got copied there at some point by accident.
Closes #157

fix: cap volume to >=0

---

script-opts/uosc.conf
scripts/uosc.lua

Chapters that end a chapter range and are matched by something other
then `.*` are now not shown when hovering over that chapter.
Closes #125

feat: don't show chapter end on hover

---

script-opts/uosc.conf

I have recently noticed that a lot of videos have "Intro" and "Outro" chapters, Should we match on those as well?

feat: better default config for chapter ranges

---

scripts/uosc.lua

The documentation cautions against using shared script properties, but
console.lua relies on the margin to not overlap with the bottom bar from
the default osc. Without support for that in uosc, using the console
was always annoying.
Now it also doesn't overlap with the uosc timeline.

feat: support `osc-margins` shared-script-property

---

scripts/uosc.lua

There is not point in specifying an opacity for a chapter range if it's not getting used :wink:.

fix: use opacity of chapter ranges

---

scripts/uosc.lua

Differentiate between parts of chapter indicator that are covered by the
progress line/bar and parts that are not.
Looks much better that way, particularly with wide indicators (e.g. the default 6 wide dots).
Performance shouldn't be that bad, as it does bounds checks and only renders what's necessary.
Not sure if this is "fix" or "feat"

fix: fancy chapter rendering

---

scripts/uosc.lua

The stream-quality control was never shown, because `is_stream` gets compared to a boolean, but `is_protocol` returned a string and so it always got filtered out.

fix: `is_protocol()` not returning a boolean

---

scripts/uosc.lua

I kept changes to a minimum for now, but there are a bunch of places that check for `state.playlist_count > 1` that could now be replaced with `state.has_playlist`.
Also there are a few places that use `mp.get_property_native('playlist-count')` instead of `state.playlist_count`. Is there a good reason for that or should those be replaced with the state property?

fix: `has_playlist` control disposition

---

scripts/uosc.lua

While things were sort of fine with `timeline_style=line`,
it was impossible to set the time to 0% or 100% when using
`timeline_style=bar`.
Now the time calculation is correct regardless of style and the
rendering is pixel perfect.
However I'm not entirely sure about the way the `timeline_style=bar` gets rendered now. It is technically correct in the sense that mouse input can go from 0% to 100% and the bar always gets displayed perfectly to the interpolated point between those two mouse input positions, so when seeking the result always lines up perfectly with the mouse input.
But that also means that when seeking to 0% the timeline bar isn't completely empty anymore, and when seeking to 100% it is also not completely full. Instead it always draws half a pixel at the edge.
Alternatively …

fix: pixel to time calculation

---

scripts/uosc.lua

This started off with noticing that a chapter line at time 0, that is supposed to be 1 pixel wide, was rendered over two pixels.
After the first commit it was a single line, but it was one pixel too far to the right. Turns out the culprit was the `time_x` and `time_width` calculation, which in turn is also connected to the cache.
The cache border indicator now doesn't overlap with the beginning and the end of the cache anymore and it always shows when there is at least a pixel between the cache start and the timeline start. That means it is always visible for progress lines with a width of 2 or more (only when there is a cache, ofc). I think it is more correct that way, but it differs from the previous behavior.
Commit messages contain some additional info.
This has a merge conflict with …

Real time width

---

scripts/uosc.lua

The hint length was calculated with the menu title, that led to wrong menu widths.
before
after
Also any submenus already have their lengths set from a previous iteration, so moving it out of the loop to the root directly.

fix: menu `hint_width` calculated from title

---

scripts/uosc.lua

The option `menu_parent_opacity` wasn't used.
Parent menus were not affected by general menu opacity, which means not only could parent menus end up more opaque then the current one, but they would also not fade out (except for the title).
With the preview and the parent menu both using 0.4 opacity, I assumed that the selected one should also use the `menu_parent_opacity`.
The scrollbar multiplied the opacity for that menu with the `menu_opacity` option, which is already included in the general menu opacity, so the scrollbar would have `menu_opacity^2`. Seems like a mistake, but if it was intentional I'll drop it again.

Menu opacity

---

scripts/uosc.lua

The border for the speed notches was always drawn with full opacity. That was particularly noticeable when the speed widget was barely visible.
before
after

Revert border_opacity for ass:rect()

---

scripts/uosc.lua

Recent changes (top bar, menu, speed) have set a precedent for opaque text on transparent background, and I think the rest of the interface should follow that trend.
Timeline and volume text is now fully opaque when the element is completely visible.
Same goes for the title of the menu, but there I wasn't sure if that was an intentional choice to make it more muted looking.
---
Btw I also noticed that in the timeline and the volume slider the background has `opacity - 0.1` while that is not the case for the menu. Not sure if that inconsistency is intentional or not. Multiplying by a factor would make more sense then subtracting anyway.

fix: text should be opaque

---

scripts/uosc.lua

If you use someone else's set of configuration files (git based), you may want to customize input.conf.

Support input-conf option

---

scripts/uosc.lua

With this the text of parent menus becomes more transparent just like their background, while still starting out with full opacity for the current menu.
Apparently the opacity for icons never even decayed in the first place? Now they also do.

fix: decay opacity of parent menus text

---

scripts/uosc.lua

Very minimal integration. Get the script here: https://github.com/po5/thumbfast
Does what you'd expect, generates and displays thumbnails. The client is in charge of positioning.  
Appears stacked on top of timestamp and chapter title if there is one.
I'd like to draw (on the uosc side) a background that acts as a border when covered up by the thumbnail, and as a placeholder while it's rendering if you don't see any issues with that, but you or @christoph-heinrich would know better how to make it look nice.  
Just keep in mind the image overlay is always rendered on top of osd overlays.
Closes #7.

feat: thumbfast intergration

---

scripts/uosc.lua

The idea behind this is that the texture tiles as if it started tiling at the anchor. This has the benefit that if multiple textured areas share the same anchor, their pattern lines up. That's noticeable with in the timeline, where if you seek forward into an uncached section, the pattern on the left would move a bit on master, but with this everything stays perfectly aligned.
It's a replacement for `align` because having both doesn't make sense. Anything that could be done with align can also be done with anchoring. Later realized the same is true for `shift`.
~The timeline is currently anchored to `fby`, but I think it looks better in motion when it's anchored to `fay`.
However while testing I noticed a problem that is also present on master with anchoring to the top of the timeline …

fix: anchor texture instead of align and shift

---

scripts/uosc.lua

Fixes the scaling as noted in https://github.com/tomasklaen/uosc/pull/213#issuecomment-1253839467
Screenshot is with 1.6 scaling factor.

fix: thumbnail decoration with scaling

---

scripts/uosc.lua

When opening the chapter menu right after opening mpv with a YouTube video that has chapters, but before the video actually loaded, it would end up in a nil error.

fix: time can be nil when creating chapter menu

---

scripts/uosc.lua

There was a problem in #238 where in the `ax`, `ay`, `bx`, `by` calculations the border size was scaled despite already being a scaled size. Depending on the scale factor, this can make a noticeable difference.
This unfortunately does not fix https://github.com/tomasklaen/uosc/pull/238#issuecomment-1255101569.

fix: border in thumbnail decoration calculation was already scaled

---

scripts/uosc.lua

In my testing the `cache-buffering-state` always starts off with nil, then 100 and then when it's a local file or a network one that loads quickly enough that it practically immediately has cached ranges there are no updates except when seeking for local files, where it will go down to 95 for me and then 100 again.
For files that need a bit longer to get cached ranges, it starts off with nil, then 100, and then 0. So take that 0 and use it as the cue that cached ranges are coming.
Also it turns out setting it in the `demuxer-via-network` observer didn't actually work because duration wasn't set yet and I just didn't notice because it got set in the `demuxer-cache-state` observer immediately after. But with recent changes that wasn't the case anymore and now I noticed.
Hopefully it won't …

feat: set uncached ranges as early as possible

---

scripts/uosc.lua

I've encountered a file that reported a duration that was 1.2 seconds longer then the end of the seekable-range, which would then show as uncached (it was also only playable until the end of the seekable-range). With the `demuxer-cache-state` reporting when the bof and the eof are cached, we can use that information to extend the first and the last cached range to then not show anything if it is fully cached.

fix: ensure cache ranges extend to 0 and duration

---

scripts/uosc.lua

So far only ad ranges from the sponsorblock script were supported, but when downloading with ytdl the sponsored parts are only a single chapter starting with `[SponsorBlock]:`. Also added `^sponsors?` because that's what I had in my old config and it never had any false positives for me.
ref #261

feat: support single chapter ads

---

scripts/uosc.lua

Something like `sponsor segment end` would in the next iteration be recognized as the start of a single chapter ad range.

fix: ads end could be recognized as single chapter ad

---

scripts/uosc.lua

With recent discoveries in https://github.com/po5/thumbfast/pull/31 this is necessary because the thumbnail size may change at any time, but it seems like a good thing to do in general.

fix: render when thumbnail size changes

---

script-opts/uosc.conf
scripts/uosc.lua

This is helpful for controls visibility in mpv [pseudo gui mode](https://mpv.io/manual/master/#pseudo-gui-mode).

feat: add is_idle dispositions

---

script-opts/uosc.conf
scripts/uosc.lua

Actually I think making those default value be `idle,paused` would be more reasonable for we do not had the logo/msg showing in idle. But I want to hear more opinions.

feat: make `*_persistency` support idle

---

scripts/uosc.lua

At present, the code implementation of the chapters menu had a little hack. 
And the active chapter behavior implemented is still not accurate by this commit https://github.com/tomasklaen/uosc/commit/5082ad0a83ce997d7321e0de55a27510081fd55c. 
Now let's deal with the behavior of the chapters correctly.

refactor: optimize code for chapters menu

---

scripts/uosc.lua

Made this when throttling seeking for thumbfast and thought you might like it because it's shorter. Behaves identically to before.
Over there it calls the function directly instead of setting a timer when time is <= 0, but that doesn't work here because then it tries to render when things aren't done initializing.

refactor: more compact `request_render()`

---

script-opts/uosc.conf
scripts/uosc.lua

It's a stripped down version of https://gist.github.com/christoph-heinrich/a3e7fdf1ed24e8625f5f9934ebe1313a
Clicks are only registered when the window can't be dragged around. I don't know if that is how you want it to behave, but with window dragging also being left click, it's ambiguous how it should behave.
Also dragging when the window is currently not dragable is also filtered out with a threshold.

fix: options.click_threshold

---

scripts/uosc.lua

Multiple code comments can conflict, fix it.
before:
after:
input.conf
```ini
z    set video-rotate 0     #menu: 测试 > rotate 0      #@click         # Comments
z    set video-rotate 90    #menu: 测试 > rotate 90     #@double_click
```

fix: compatible with multiple comments

---

scripts/uosc.lua

Another wrong calculation revealed by (mostly) accurate text widths.

fix: buffer time x bounds calculation

---

scripts/uosc.lua

Having a (mostly) accurate text widths has revealed a mistake in the cut coordinate calculation.
before:
after:

fix: menu title/hint clipping

---

scripts/uosc.lua

#301 broke touch input, because the `mbtn_left` event happens before the position update from `mouse-pos`, so touch would always register a click on the old position, making the UI practically unusable.
`ignore_hover` is needed to make things work on Wayland in windowed mode because of the window dragging triggering a `hover == false`.
---
For decent touch support, scrolling by dragging in the menu is still missing, but I'll tackle that some other day.

fix: touch input

---

scripts/uosc.lua

When you slowly move the timeline to left, it automatically moves to right.
For a better experience, I would like to temporally disable the pause indicator. How can I do this?

fix: pause while dragging the timeline

---

scripts/uosc.lua

It now supports checking URLs like this: `magnet:?`

fix: support checking URL without slashes

---

scripts/uosc.lua

There is currently this PR for mpv https://github.com/mpv-player/mpv/pull/10779 and that algorithm would be a good improvement here too.
This maintains the current behavior + better sorting of numbers.
The for loop always only ran once, so I've removed the loop and just let it check the first character.
I actually tried fixing up the loop to iterate over each character (until a difference is found), but that led to a directory with lots of `N.mp3` files having `11.mp3` before `9.mp3` with all other numbers being correctly sorted, and the function always returned that 11 is not smaller then 9, so I have no idea how it ended up like that and I didn't want to spend hours trying to debug this.

feat: better file sorting

---

scripts/uosc/lib/menus.lua
scripts/uosc/lib/utils.lua

I measured a ~15 times speedup on that 1700 files folder I made out of dyphires config.
Numbers with leading zeros are now sorted after identical numbers without leading zeros.
ref. https://github.com/tomasklaen/uosc/pull/338#issuecomment-1290137738

perf: faster filename sorting

---

scripts/uosc/lib/utils.lua

Restore the sorting behavior from before #341
Also comes with a small performance improvement, but hardly worth mentioning. (~5%)
Ref. https://github.com/tomasklaen/uosc/pull/341#issuecomment-1290954070

fix: restore leading zero sorting

---

scripts/uosc/lib/std.lua
scripts/uosc/lib/utils.lua

This is not just a performance improvement, but a bug fix as well. I used to not be possible to get to the root directory on linux, but now that works.
The loop I measured in #344 went from ~880ms down to ~40ms with this. There is still a lot of room for improvement, but this is already huge.
Splitting `working_path` with `last_index_of()` had identical performance to `utils.split_path()`, but using the built-in function is less code.
Creating `filename` and `extension` now only contributes ~1ms to the total time instead of ~20ms.

perf: optimize serialize_path

---

scripts/uosc/lib/std.lua
scripts/uosc/lib/utils.lua

Does not convert backslashes to slashes or vice versa anymore.
Backslash is a valid character on Unix filesystems, so converting it to slash can actually break things.
I don't think it's possible to encounter a slash in a path on windows, except maybe from the `default_directory` option. If that's really a problem, we should sanitize that option at startup instead of always substituting in `normalize_path`.
This together with #346 brings the measured time on that file loop on my test directory down to ~18ms, getting surprisingly close to the time from #344.

perf: optimize normalize_path

---

scripts/uosc_shared/elements/Menu.lua

Without checking if mbtn_down happened first in the menu, it is possible to select an item right after opening the menu from the controls. (mbtn_down on control opens menu, mbtn_up selects item in menu)
That is really annoying when the playlist menu is big enough to overlap with the control for opening the playlist.

fix: selection on mbtn_up requires mbtn_down first

---

scripts/uosc_shared/lib/menus.lua
scripts/uosc_shared/lib/std.lua
scripts/uosc_shared/lib/utils.lua

This also addresses displaying `/` as path separator on windows.
@dyphire can you please test that it works fine on windows?
ref. https://github.com/tomasklaen/uosc/pull/344#issuecomment-1293393638

fix: directory name when browsing files

---

scripts/uosc_shared/elements/Button.lua
scripts/uosc_shared/elements/Speed.lua

fix: controls activating when overlapping chapter is clicked

---

scripts/uosc_shared/elements/Timeline.lua

Fixes https://github.com/tomasklaen/uosc/issues/49#issuecomment-1348022899
This made me realize that a-b loop indicators aren't clickable even though they look the same as chapter indicators. Do we want that?

fix: A-B loop crash

---

script-opts/uosc.conf
scripts/uosc.lua
scripts/uosc_shared/elements/Timeline.lua

Resolves #397
I used `playtime-remaining` and `time-remaining` because this is how the are described in mpv documentation.

feat: add destination_time option and deprecate total_time

---

scripts/uosc.lua

Looks like `mouse-pos` can be `nil`. Adding a simple function guard should suffice.
Closes #413

fix: `mouse-pos` can be nil

---

scripts/uosc_shared/elements/Timeline.lua

This adjusts `buffered_time_threshold` to behave the way described in https://github.com/tomasklaen/uosc/issues/421#issuecomment-1377084759.

tweak: buffered time threshold based on displayed value

---

scripts/uosc_shared/elements/Timeline.lua

Without this the buffered time would get too close to the remaining time.

fix: buffered time respects minus in time remaining

---

scripts/uosc_shared/lib/utils.lua

I've encountered filenames like `EP.1.v0.1080p.mp4`, which resulted in suboptimal sorting (e.g. episode 11 between 1 and 2). Dolphin however sorted them correctly.
I've tested it with the examples from the [original algorithm](https://notebook.kulchenko.com/algorithms/alphanumeric-natural-sorting-for-humans-in-lua).
Regarding performance it seems to be a bit of a toss up. On one of my first folders the performance has improved slightly (~7ms vs ~6ms) but on the second one it has decreased (~22ms vs ~25ms).
This will sort worse for names like `234.456465.345.467456`, but that's probably fine.

feat: better alphanumerical sorting

---

README.md
scripts/uosc.lua

This allows 3rd party scripts to replace the handling of built in uosc key bindings with their own logic.
Example that replaces uosc's basic stream quality menu with christoph-heinrich/mpv-quality-menu:
```lua
mp.commandv('script-message-to', 'uosc', 'reroute-binding', 'stream-quality', 'script-binding quality_menu/video_formats_toggle')
```
Any objections or suggestions? Maybe `reroute` is not the best name to describe this?
---
ref #429

feat: added an API to reroute uosc key bindings

---

README.md
scripts/uosc.lua
scripts/uosc_shared/lib/menus.lua

Creating the new table is required to appease the type checker. I also had a version that just told the type checker to shut up, but it required a temporary variable, making the whole thing not really any shorter.
This doesn't work with `update-menu` because there is currently no way of updating `opts` and I'm not sure that's useful enough to make that happen.
Also there was a bug where `opts.submenu_id` got set instead of `opts.submenu`.
Closes #448

feat: add `on_close` command to menu API

---

scripts/uosc_shared/lib/utils.lua

I've recently encountered a few videos with false positives for `endings`. Turns out it's because chapters ending with e.g. 'trending' would be detected as an ending. To fix that I've now applied the same pattern for 'ending' as was already used for 'ed'.
While doing that I've noticed that 'opening' and 'closing' were also the same way, so I've applied the same thing to them too, but since I've never actually noticed any problems with them, I've made it a separate commit. Also I don't know if having all three variants even makes sense for all of them.
This is a draft because I'm not sure about the change and it could certainly benefit from testing and discussion.
A collection of examples of what should and shouldn't be detected for each kind would take a lot of the guesswork out of such …

Chapter range patterns

---

scripts/uosc.lua

A recently merged PR https://github.com/mpv-player/mpv/pull/11226 made the console use the new `user-data` property instead of shared-script-properties, resulting in our margins being ignored.
This sets the `user-data/osc/margins` property in addition to the old shared-script-property to keep compatiblity with older mpv versions.
The `user-data` property was introduced in https://github.com/mpv-player/mpv/pull/11013.

Add support for the new user-data property

---

scripts/uosc.lua
scripts/uosc_shared/elements/Button.lua
scripts/uosc_shared/elements/Element.lua
scripts/uosc_shared/elements/Elements.lua
scripts/uosc_shared/elements/Menu.lua
scripts/uosc_shared/elements/Speed.lua
scripts/uosc_shared/elements/Timeline.lua
scripts/uosc_shared/elements/TopBar.lua
scripts/uosc_shared/elements/Volume.lua
scripts/uosc_shared/lib/text.lua
scripts/uosc_shared/lib/utils.lua

PR for testing and feedback if anyone is interested. I wanted a bit different and "prettier" API initially, but I've realized this is all we need.
The core of this is that `mbtn_left_down/up` and `wheel_down/up` events are now only fired on a `cursor` object, which now looks like this:
```lua
cursor = {
x = 0,
y = 0,
hidden = true,
hover_raw = false,
-- Event handlers that are only fired on cursor, bound during render loop. Guidelines:
-- - element activations (clicks) go to `mbtn_left_down` handler
-- - `mbtn_button_up` is only for clearing dragging/swiping
on_primary_down = nil,
on_primary_up = nil,
on_wheel_down = nil,
on_wheel_up = nil,
-- Called at the beginning of each render
reset_handlers = function()
cursor.on_primary_down, cursor.on_primary_up = nil, nil
cursor.on_wheel_down, …
```

refactor: cursor events consolidated into one interface

---

scripts/uosc_shared/elements/Menu.lua

Long titles with short items would lead to the title touching the edge of the menu, which doesn't look good.
Adding padding like is already with the items remedies this.

tweak: add padding to title

---

scripts/uosc.lua

The keybindings 'mbtn_left' and 'wheel' were enabled/disabled on every render, resulting in log files being spammed with corresponding debug messages.
To avoid that only call the enable/disable function when the current decision is different to the last one.
Closes #491

fix: only enable/disable mouse keybinds when they change

---

script-opts/uosc.conf
scripts/uosc.lua
scripts/uosc_shared/elements/Element.lua
scripts/uosc_shared/elements/TopBar.lua

The margins were already set for `osc-margins` and `user-data/osc/margins`, but osd messages have their own properties `osd-margin-y` and `osd-margin-x`.
Offsetting `osd-margin-y` by our margin prevents overlap of osd messages with the GUI.
ref. https://github.com/tomasklaen/uosc/discussions/498

feat: apply margin to `osd-margin-y`

---

scripts/uosc_shared/lib/text.lua

Italic doesn't really make each character take up more space, but rather adds a fixed width to the whole text independent of text length.
I've checked a bunch of fonts and for all of them the added width was between 0.17 and 0.23 of the text size, so I'd expect 0.2 to work well for everything out there except for maybe some extreme outliers.

tweak: treat italic as a width offset rather then a factor

---

scripts/uosc.lua

With the change to use the new `platform` property, the platform 'macos' also got renamed to 'darwin', but the platform checks were not adjusted to the new name.
Closes #512

fix: check for the platform 'darwin' instead of 'macos'

---

scripts/uosc_shared/elements/Menu.lua

The translation function was repeatedly called when a menu title bar was displayed.
Also escape title post-translation.

perf: cache menu title translation

---

tests/test_ranges.lua

That's the test file I've used for #454.
It's probably better when it's in the repo in case someone else wants to try changing those patterns.
Ideally we would import utils.lua and share the `simple_ranges` table (and maybe even the code that applies the patterns on the capters), but that's good enough for now.

test: add chapter ranges pattern tests

---

scripts/uosc.lua
scripts/uosc_shared/lib/menus.lua

The channel count in track list couldn't be translated.
Also translate mpv's hardcoded entries in the audio devices list.

fix: translate audio channels and devices list

---

scripts/uosc_shared/elements/TopBar.lua

Need to add translation, after https://github.com/tomasklaen/uosc/pull/532 and https://github.com/tomasklaen/uosc/pull/534.

fix: translate topbar when no file

---

scripts/uosc_shared/intl/de.json
scripts/uosc_shared/intl/es.json
scripts/uosc_shared/intl/fr.json
scripts/uosc_shared/intl/ro.json
scripts/uosc_shared/intl/zh-hans.json
scripts/uosc_shared/lib/utils.lua

As well as handling of `(unnamed)` for mkv demuxer, empty string for disc demuxer.
https://github.com/mpv-player/mpv/blob/c5211dbf4ae38583b4a55ab63c5c07f8547f73b8/demux/demux_mkv.c#L964
https://github.com/mpv-player/mpv/blob/c5211dbf4ae38583b4a55ab63c5c07f8547f73b8/demux/demux_disc.c#L285
Other demuxers either don't supply a title, or use NULL as a fallback value.
Took care of German and Simplified Chinese too, since those have verified translations on Google.

fix: translate fallback chapter title

---

scripts/uosc_shared/elements/Timeline.lua

Only really matters for absurdly high `window_border_size` values (>10).

fix: take window_border_size into account for thumbnail positioning

---

scripts/uosc_shared/lib/ass.lua

(Disregard the overextended timeline)

fix: take window_border_size into account for tooltip positioning

---

scripts/uosc_shared/elements/Menu.lua

When moving around items the scroll position doesn't update, which can be annoying when moving things around in a large playlist. Instead the menu should scroll with the moved item.
The problem with this is that scrolling itself causes a render, which means the menu gets rendered once with the updated scroll position but with the playlist item still in it's old position, and then again when the playlist itself gets updated, leading to a short visual artifact.
I can't think of a good solution to this.
It's possible to stop scrolling from requesting renders and instead request renders in other places instead, but that would still lead to problems when something else (e.g. playback position update) causes a render.
It's also possible to preemptively move the menu item in the menu itself, but …

feat: scroll to new position after moving item in menu

---

scripts/uosc_shared/lib/text.lua

Capping the character byte count to the remaining string length prevents out of bounds access.
Closes #515

fix: cap char byte count of UTF-8 to string length

---

scripts/uosc/elements/Menu.lua

When a script-defined menu gets updated with fewer items than it previously had, the user's selected index doesn't get clamped or reset, leading to this crash when pressing Enter:
```lua
[uosc] 
[uosc] stack traceback:
[uosc]  /home/eva/.config/mpv/scripts/uosc/elements/Menu.lua:499: in function 'open_selected_item'
[uosc]  /home/eva/.config/mpv/scripts/uosc/elements/Menu.lua:514: in function </home/eva/.config/mpv/scripts/uosc/elements/Menu.lua:514>
[uosc]  (...tail calls...)
[uosc]  /home/eva/.config/mpv/scripts/uosc/elements/Menu.lua:678: in function 'fn'
[uosc]  mp.defaults:230: in function 'fn'
[uosc]  mp.defaults:65: in function 'handler'
[uosc]  mp.defaults:380: in function 'handler'
[uosc]  mp.defaults:510: in function 'call_event_handlers'
[uosc]  mp.defaults:552: in function …
```

fix: crash when a script menu update renders selected index unavailable

---

scripts/uosc/lib/utils.lua

We were already using the same sorting algorithm as autoload.lua, but with the addition of a custom symbol order. However that symbol order was only applied to the first character, so when sorting absolute paths it doesn't actually make a difference.
Using the exact same algorithm for autoload.lua and uosc also makes it easier to apply any future improvements from one to the other.

tweak: remove symbol order from sorting algorithm

---

scripts/uosc/elements/Menu.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/lib/std.lua
scripts/uosc/main.lua

So far any dragging in a sufficiently long video would cause fast seeks. That was annoying when dragging slowly, because the seek would always go back to the last keyframe.
With the adaption of the drag speed measurement from the menu, we can decide if we want to do fast seeks based on cursor speed.
Closes #607

feat: fast seek in timeline based on drag speed

---

scripts/uosc/elements/Timeline.lua
scripts/uosc/lib/ass.lua
scripts/uosc/lib/text.lua
scripts/uosc/lib/utils.lua

Depending on the current frame of the video the hovered time and chapter title might be hard to read.
Do we even want something like this?
And if so, how big should the background margins be? Should they be adjusted to always line up with the background of the other ones, like is the case in the screenshot?
Currently it's based on font size, but of course that doesn't necessarily line up neatly with the other backgrounds, and it uses the timeline opacity (0.7 in the screenshot).
I didn't have a good sample on hand, but here is what it currently looks like.
P.S. I had to change the line splitting in the wrap_text() because otherwise it always added an additional empty line at the end, which led to the wrong line count.

feat: add a background to timeline tooltips

---

scripts/uosc/elements/Menu.lua

The menu item representing an empty menu is supposed to be not selectable, however it was possible to select it with the mouse. That results in a crash in the chapters menu because it subtracts one from the value, which is "ignore" for the "Empty" item.

fix: crash when selecting "Empty" in chapters menu

---

scripts/uosc/elements/TopBar.lua

`top_bar_title` was checked like a bool, but it is a string, so it was always treated as true.
Playlist checks were also missing.

fix: top bar enabled checks

---

scripts/uosc/elements/Menu.lua

It was possible for not selectable items to be selected via page up/down as well as when updating the menu.
Page down now goes to the next best selectable item after adding to the index, like is the case for `next()`, with a fallback to an earlier index.
Page up is the same as page down but inverted direction.
Updating the menu now chooses the closes selectable item to the intended index.

fix: don't select not selectable items

---

scripts/uosc/elements/Controls.lua
scripts/uosc/elements/Element.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/PauseIndicator.lua
scripts/uosc/elements/Speed.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/TopBar.lua
scripts/uosc/elements/Volume.lua
scripts/uosc/elements/WindowBorder.lua
scripts/uosc/main.lua

Options can be changed during runtime by changing `script-opts`.
So far such option changes were simply ignored, but basic support for some options is very easy to achieve.
This is a very half baked thing, so far only `time_precision` and `font_scale` have been tested. Options that are as trivial to update as `font_scale` should also work without a problem, but other options need some additional work (similar to `time_precision`).
Also changes to e.g. `proximity_out` don't execute the same sanity checking as it does during initialization. We could move all the initialization stuff into a function that then gets executed in the update callback, which is trivial for the sanity checking, but requires some more work for the `config` table. Opinions?

feat: initial support for updating options at runtime

---

scripts/uosc/elements/Menu.lua

It was possible for menus with titles to clip on the bottom edge.
They also weren't sized and positioned the same as menus without titles.

fix: menu height and positioning

---

scripts/uosc/elements/Controls.lua

A speed control diffinition like e.g. `speed:{1.8}` would result in a crash because the `scale` gets set to `{1.8}` which isn't a string lua can convert to a number on the fly.
Fixes #632

fix: crash when using wrong syntax for speed scale

---

scripts/uosc/elements/Menu.lua

It attempts to do what select_by_offset already does but worse and the check also couldn't have been right.
Additionally select_by_offset() was missing a request_render(), but that seems to never actually make a difference.

fix: selected_index norm in reset_navigation()

---

scripts/uosc/lib/utils.lua
scripts/uosc/main.lua

Shuffle now has its own history which inherits from `state.history` to not break the prev button.
It can populate the history with random items in both directions.
When shuffle is disabled, it clears its history (so all next states if any), but next time it's enabled it'll inherit `state.history` for its prev states again.
Did I miss anything?
ref #635

fix: shuffle history couldn't go back more than once

---

README.md
script-opts/uosc.conf
scripts/uosc/elements/Menu.lua
scripts/uosc/main.lua

A search can be started with `ctrl+f` or `/` and stopped with `esc`.
It currently works for anything using `create_self_updating_menu_opener()`, `open_file_navigation_menu()` and menus opened by scripts.
Internal menus do a case insensitive search of the title and hint, while scripts have to do their own filtering.
The reason why scripts have to do their own filtering is because that allows scripts like [memo](https://github.com/po5/memo) to do proper filtering despite splitting up the results in pages.
I've use a little bit of code from console.lua ([1](https://github.com/mpv-player/mpv/blob/3972fd1be4ef0f8fe083b43e41c3e06104003a3c/player/lua/console.lua#L258-L260) [2](https://github.com/mpv-player/mpv/blob/3972fd1be4ef0f8fe083b43e41c3e06104003a3c/player/lua/console.lua#L769-L770)), but …

feat: make the menu searchable

---

scripts/uosc/elements/Menu.lua

The title was lowered, but not the query.
As a result searching for uppercase letters would never match anything.
Fixes #637
I must have accidentally done one too many undo or something, after all the whole point of making it into a local variable was for the lowering...

fix: case insensitive menu search

---

scripts/uosc/main.lua

mpv is about to remove `shared-script-properties`, which will cause `utils.shared_script_property_set` to be nil.
Check for it's existence before calling it.
https://github.com/mpv-player/mpv/pull/12456
Whenever our latest supported version is after 36.0 we can drop that call altogether.

fix: prepare for shared-script-properties removal

---

scripts/uosc/main.lua

Due to a recent change in mpv writing to `playlist-pos` doesn't restart playback anymore, which was necessary for the format change to work for the current file.
https://github.com/mpv-player/mpv/commit/4b2276b730c8542649b665aaec187e1c7e3b2612

fix: stream quality selection

---

scripts/uosc/elements/Menu.lua
scripts/uosc/lib/text.lua

I don't really understand why title and hint characters should be concatenated.
It might make some sense when the title is only one word, but otherwise it might lead to unexpected results.
I tried also a different implementation based on `find` instead of `gmatch` that I expected to be faster, because it only allocated half as many strings, but it turned out to be the same speed.
Ref. https://github.com/tomasklaen/uosc/pull/625#issuecomment-1732069651

feat: search first character of each word

---

scripts/uosc/elements/Menu.lua

Currently the text does not advance to the left when spaces are entered, which must mean that libass trims any trailing spaces. Appending a ZWNBSP at the end prevents any trimming.

fix: render spaces at the end of the search query

---

README.md
scripts/uosc/elements/Menu.lua

Each (sub)menu can now enable palette mode by setting its `palette` property to `true`.
In this mode:
- search input is always visible, doesn't have to be enabled, and can't be disabled
- `title` is used as input placeholder while search is empty
Any suggestions/bugs/comments?

feat: palette menus

---

README.md
scripts/uosc/elements/Menu.lua
scripts/uosc/main.lua

Ref. https://github.com/tomasklaen/uosc/issues/587#issuecomment-1682294760

Menu script-message changes

---

README.md
scripts/uosc/elements/Menu.lua
scripts/uosc/lib/menus.lua

`search_recursive` makes user search look into submenus as well, effectively flattening the menu for the duration of the search.
With this, we don't need a new `menu-palette` command anymore. It's just built into the default one:

feat(api): added `search_recursive` prop to menus

---

scripts/uosc/elements/Menu.lua

I changed that logic a bit at some point during development and apparently never tested with non ascii characters since then :disappointed: 
It used to go to the first byte of the multi byte utf8 character and cut off everything after that, instead of going to one byte before that.

fix: deletion of unicode characters

---

README.md
scripts/uosc/lib/menus.lua
scripts/uosc/main.lua

feat: `inputs` command to display a palette menu with all user defined inputs

---

script-opts/uosc.conf
scripts/uosc/elements/Button.lua
scripts/uosc/elements/Controls.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/Speed.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/TopBar.lua
scripts/uosc/elements/Volume.lua
scripts/uosc/elements/WindowBorder.lua
scripts/uosc/lib/ass.lua
scripts/uosc/main.lua

Removed options:
```
timeline_size_fullscreen
controls_size_fullscreen
volume_size_fullscreen
menu_item_height_fullscreen
menu_min_width_fullscreen
top_bar_size_fullscreen
```
Additionally, `ui_scale` has been renamed to `scale`.
The scaling can now be controlled by these two new options:
```
scale=1
scale_fullscreen=1.3
```
closes #543

feat!: reworked config options for fullscreen scale adjustments

---

scripts/uosc/elements/WindowBorder.lua

`top-bar` is only relevant on windows
Ref. https://github.com/tomasklaen/uosc/pull/643#issuecomment-1750853705

fix: window border enable logic for non windows

---

scripts/uosc/elements/Menu.lua

I hope I didn't miss anything.
Fixes #671
<hr/>
While testing this I noticed that the context menu uses recursive search, but only on the root menu, submenus perform a regular search. Is that intentional?
It's also missing from the menu data structure in the readme, so it's not clear if it's supposed to be a per menu or a global option.

fix: updating the menu while using the internal search

---

scripts/uosc/elements/Volume.lua

d2febcbd4709001f5db61b4d6befe545ab65d578 forgot the second parameter, resulting in a crash because it's nil.

fix: volume slider crash when no audio

---

scripts/uosc/elements/Menu.lua

It's particularly noticeable for active items.
before
after

tweak: remove text shadow in menu

---

README.md
scripts/uosc/elements/Menu.lua

`nil` being a valid menu type in the provided property was a mistake.
For backwards compatiblity we also set `shared-script-properties` now.
Fixes #672

fix: user-data/uosc/menu/type being nil means closed

---

scripts/uosc/elements/Menu.lua

Doesn't yet have any of the non-linear stuff, but it's already a big improvement.
ref https://github.com/tomasklaen/uosc/pull/665#issuecomment-1745887138
For comparison with the screenshot in the comment:

feat: clamp title and hint size to min 20% width

---

script-opts/uosc.conf
scripts/uosc/elements/Curtain.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/Speed.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/TopBar.lua
scripts/uosc/elements/Volume.lua
scripts/uosc/elements/WindowBorder.lua
scripts/uosc/lib/ass.lua
scripts/uosc/main.lua

These options have been removed:
```
timeline_opacity
timeline_chapters_opacity
volume_opacity
speed_opacity
menu_opacity
menu_parent_opacity
top_bar_title_opacity
window_border_opacity
curtain_opacity
```
and replaced with one comma delimited `opacity` list to override all of the above and some new default opacity values.
Example:
```
opacity=timeline=0.5,title=0.5
```
List of opacity values available for override and their current defaults:
```
timeline=.9
position=1     # timeline progress or line
chapters=0.8
slider=0.9     # background of all sliders, such as volume
slider_gauge=1 # value bar of all sliders
speed=0.6
menu=1
submenu=0.4
border=1       # window border
title=1        # window title
tooltip=1      # tooltip background
thumbnail=1    # thumbnail border
curtain=0.5
``` …

feat!: reworked opacity options

---

README.md
scripts/uosc/elements/Menu.lua
scripts/uosc/lib/menus.lua

When defining menu items in `input.conf`, it is now possible to add an un-selectable+muted+italic menu items by using `#` as key, and omitting the command:
```
```
You can also add a separator between previous and next item by using `---` as title:
```
```
closes #69

feat: support for creating menu titles and separators in `input.conf`

---

README.md
installers/unix.sh
installers/windows.ps1

I haven't tested the script for Linux & macOS. If anyone could, it'd be nice :) It should install current latest stable.
I also want to figure out if we can provide a `uosc/update` command that people can just run from their menu and update uosc in the background.

feat: scripts to install or update uosc with a single line

---

README.md
script-opts/uosc.conf
scripts/uosc/elements/BufferingIndicator.lua
scripts/uosc/elements/Controls.lua
scripts/uosc/elements/Curtain.lua
scripts/uosc/elements/CycleButton.lua
scripts/uosc/elements/Element.lua
scripts/uosc/elements/Elements.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/PauseIndicator.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/TopBar.lua
scripts/uosc/elements/Volume.lua
scripts/uosc/elements/WindowBorder.lua
scripts/uosc/lib/ass.lua
scripts/uosc/lib/std.lua
scripts/uosc/lib/utils.lua
scripts/uosc/main.lua

Allows disabling elements and various indicators by adding their IDs to the list:
```conf
disable_elements=timeline,audio_indicator
```
Also includes a new script message listener `disable-elements`, that allows scripts to do the same thing:
```lua
local id = mp.get_script_name()
mp.commandv('script-message-to', 'uosc', 'disable-elements', id, 'timeline,audio_indicator')
```
It'll register what elements each script wants disabled. The element will be enabled only when it was not disabled by neither user nor any script.
To cancel or re-enable the elements, pass an empty list:
```lua
mp.commandv('script-message-to', 'uosc', 'disable-elements', id, '')
```
ref #686, closes #592
---
This was way more work then I expected :(
I hope I didn't introduce many bugs.
Also, is it really not possible …

feat: added `disable_elements` option and `disable-elements` script message

---

scripts/uosc/lib/cursor.lua

Essentially same problem as in https://github.com/tomasklaen/uosc/pull/327.
Position update needs to happen _before_ the button event.
Broke with 8d85068b7c457c8e17599a350ecbb530988189f1 and I didn't notice until now because I don't use mpv with touch input on my laptop all that often.

fix: position update before mbtn_left down handler

---

scripts/uosc/elements/Menu.lua

Most of the time flinging on a touch device looked like it didn't work, but it turns out that it simply didn't render.

fix: render after menu fling

---

scripts/uosc/elements/Button.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/Speed.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/TopBar.lua
scripts/uosc/elements/Volume.lua
scripts/uosc/lib/cursor.lua
scripts/uosc/lib/menus.lua
scripts/uosc/lib/std.lua
scripts/uosc/lib/utils.lua

This not only prevents the problem described in the issue, but it also allows all rendered elements to be tapped, even when a different element was hovered on last render.
It still requires hovering an element before being able to tap anything, but that's probably unavoidable without always having mbtn events registered. Registering clicks on mbtn up as well we mbtn down could alleviate that problem for buttons, but that wouldn't work universally.
Known problems
* `cursor.allow_dragging = true` in the top bar only works when the cursor was already on the top bar on the last render, not a big deal
* ~~timeline chapter markers require hover before being clickable because of their round hitbox. We can either make the hitbox squares or make `cursor:find_main_handler()` able to deal with …

Fix touch input handlers

---

README.md
script-opts/uosc.conf
scripts/uosc/elements/BufferingIndicator.lua
scripts/uosc/elements/Curtain.lua
scripts/uosc/elements/Element.lua
scripts/uosc/elements/Elements.lua
scripts/uosc/elements/Menu.lua
scripts/uosc/elements/PauseIndicator.lua
scripts/uosc/elements/Timeline.lua
scripts/uosc/elements/Updater.lua
scripts/uosc/elements/WindowBorder.lua
scripts/uosc/main.lua

https://github.com/tomasklaen/uosc/assets/47283320/93ce48e3-02d3-4df9-85cc-3af8df7c3b1b
If anyone can test it on linux/mac, it'd be great, but be aware that it's going to replace your current uosc in `~/.config/mpv` with the latest release, which is 4.7.
The only issue this has now (that I know of) is that to do a windows portable update, I need to know the path to mpv binary so the updating process can run in its working directory.
Is there a way to get it somehow? And is there some arg to `mp.command_native_async()` to set the working directory? Can't find info on any of these. But I haven't tried _super_ hard, so hopefully it's still doable :)

feat: added `update` command to update uosc

---

README.md
scripts/uosc/main.lua

Scripts that offer a UI variant based on the uosc menu might get called right after startup before uosc manages to respond to their `get-version` request. As a result the non uosc UI will be shown. If we proactively broadcast the version as soon as possible then we minimize the chance of that happening.
That came up because of https://github.com/po5/memo/issues/16, where in a little test script I had to add a timeout of >= 1 to get the uosc menu, anything less would not reliably open the uosc menu.
With the early broadcast a timeout of 0.8 is enough, which is still not great, but the chance is also greatly increased with smaller values. I'll have to look if something can be done about that on the mpv side at some point, but it's better then nothing.

feat: broadcast uosc version as early as possible

---

README.md
scripts/uosc/elements/Menu.lua

`escape` now only closes the menu, and nothing else (before it would clear search if present first).
New shortcuts:
- `ctrl+backspace` - Delete search query by word.
- `shift+backspace` - Clear search query.

feat: improved `escape` and `backspace` behavior in menus

---

scripts/uosc/elements/Timeline.lua

Fixes #373
<hr/>
Now that elements can be created/destroyed at runtime, an alternative way of dealing with script-opts updates would be to destroy and recreate everything. If it works on startup, it'll also work during runtime.

fix: runtime updates for progress option

---

dist/scripts/uosc/elements/Menu.lua

Fixes #753
<hr/>
I'm somewhat bothered by the inconsistency in which things are included where in the x and y calculation of the menu, but that can be changed some other time.

fix: add padding to menu width calculation

---

tools/build

Without this I get errors like:
```
tools/build: line 17: syntax error near unexpected token `elif'
tools/build: line 17: `elif [ $1 == "intl" ]; then'
```
and
```
tools/build: line 17: [: ==: unary operator expected
```
I didn't get around to testing this sooner, and neither did anybody else apparently :upside_down_face:

fix: script syntax

---

src/uosc/elements/Menu.lua

Updating items during an active search always selected the first item.
I'm not sure if I should put that if in a new loop or not.
Do you prefer those `if`s to be on a single line now or not? Not sure now after those style changes.

fix: keep selected index on menu update during search

---

src/uosc/lib/cursor.lua

`Element:update_proximity()` checks for `cursor.hidden`, which is why we have to update that before updating the proximities.
Also it doesn't make sense to not record the first cursor position on enter.

fix: correctly update proximities on mouse enter and record position

---

src/uosc/lib/cursor.lua

The cursor isn't allowed to autohide while hovering elements, so the UI shouldn't autohide either. Otherwise this leads to the situation where the UI autohides while e.g. hovering the timeline, and then the cursor autohides afterwards because it's not hovering anything anymore.
The `self.autohide_timer:kill()` in function `cursor:autohide()` doesn't change anything functionality wise, but without it the timer keeps periodically moving the mouse to `(inf, inf)` which is unnecessary and annoying when debugging cursor position related stuff.
The `self:queue_autohide()` in `cursor:decide_keybinds()` is necessary because when e.g. the cursor moves 1px off of an element then during the position update there are still the bindings for that element, so UI autohide is prevented, but then on the …

fix: only autohide UI when the cursor autohides

---

src/uosc/elements/Menu.lua

Opening a large menu with a selected item would not scroll all the way to that selected item if there was a menu update during the initial fling.
That's noticeable when opening the menu from my subtitle-lines script while the video is playing. When the active subtitles change right after opening the menu, the initial fling gets interrupted and it gets stuck somewhere in the middle.

fix: don't cause a fling in update_dimensions()

---

src/uosc/elements/Menu.lua

I don't think there is currently a use case for this, but maybe there will be at some point and it doesn't hurt.
This would enable scrolling to some item on menu open even with `mouse_nav` set, but currently any place that can open a menu with `selected_index` set doesn't have `mouse_nav` set.

tweak: always scroll to selected index on menu open

---

src/uosc/elements/Menu.lua

When opening a submenu with id the parents got selected, but not scrolled to. So it was possible that the selected index was out of view, which is odd when then navigating to the parent menu (it also makes sense visually).

fix: scroll parent menus when opening menu by id

---

src/uosc/lib/intl.lua
src/uosc/lib/std.lua

The crash happens because `utils.parse_json(json_string)` returns `table, nil, ''`, which then get passed as varargs to `table_assign()`, which doesn't like that string as argument.
I don't know if we should fix the crash by checking that the type is a table, because technically anything other then a table is a violation of defined argument types of the function and therefore it might be preferable the fix the call site (intl.lua:59 and intl.lua:63) instead?
Fixes crash from #792

Fix interpreter crash

---

src/uosc/elements/TopBar.lua

ref. https://github.com/tomasklaen/uosc/issues/203#issuecomment-1811429746

fix: make maximize workaround windows specific

---

src/uosc/main.lua

On Windows trying to open a path that contains a comma fails unless there's a space anywhere in the path, adding a trailing space to the end of it doesn't seem to bother `explorer /select,` and forces proper quotations.
Here's a bit more detail about this https://github.com/mpvnet-player/mpv.net/issues/580#issuecomment-1819365741

fix: `show-in-directory` issue opening paths containing a comma (win)

---

src/uosc/elements/BufferingIndicator.lua

The element id didn't match the id in the constructors table or the description in the config. Consequently it was possible to disable the indicator at startup, but once it was instantiated it wasn't possible to remove it again.
Fixes #808

fix: buffering indicator id

---

src/uosc/main.lua

This is useful when running on a platform builds of `ziggy` aren't provided for... or when using a distro-provided build.
The idea for this patch originated in NixOS/nixpkgs#270962, as I needed a way to point `uosc` at the nix-managed build of `ziggy`.

main.lua: Support overriding `ziggy_path` via environment variable

---

src/uosc/lib/utils.lua

Thank @stax76 for providing the code. See-Also https://github.com/mpvnet-player/mpv.net/issues/575#issuecomment-1817413401, https://github.com/jonniek/mpv-playlistmanager/pull/128
> The current sorting function `sort_filenames()` is very different from the sorting in Windows Explorer.
> Microsoft does not open source the sorting algorithm, but does provide the API, see [StrCmpLogicalW](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcmplogicalw).
> 
> Fortunately, [LuaJIT ](https://luajit.org/) can call Windows API, and most popular mpv windows build are builds with LuaJIT, such as [shinchiro/mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake).
> 
> So if OS is Windows and mpv builds with luaJIT, we can use the win32 API to ensure that the …

feat: use the sorting function `StrCmpLogicalW` provided by the win32 API

---

src/uosc/lib/text.lua
src/uosc/main.lua

Caching the zero represenation sounds like a good idea, until the precision gets changed and then e.g. 01:40:23.13 returns -00:00:00.0 because it has the same amount of characters, messing up our width estimation and pseudo monospace thingy.
Clearing the cache on options change avoids such conflicts.
Fixes https://github.com/tomasklaen/uosc/issues/834#issuecomment-1896443240

fix: timestamp zero representation caching

---

src/uosc/elements/Menu.lua

This should have been part of #759, but never encountered it during testing.
When the selected index is kept, then the scroll position should also stay the same. Otherwise it's annoying when there are enough search results that scrolling is required.

fix: don't scroll to top on menu update during search

---

src/uosc/elements/Button.lua
src/uosc/elements/Menu.lua
src/uosc/elements/Speed.lua
src/uosc/elements/TopBar.lua
src/uosc/elements/Updater.lua
src/uosc/elements/Volume.lua
src/uosc/lib/cursor.lua
src/uosc/lib/utils.lua
src/uosc/main.lua

This moves click threshold handling to cursor zones, and reworks them a bit. Each zone can now set `window_dragging = false` in their hitbox (defaults to `true` when `nil`), which will disable window dragging only when cursor is on top of that zone.
Resolves #820
---
There's a weird issue with this. If I click the close window button with this PR, the window closes, but the process doesn't actually exit. I have to Ctrl+C it in the console 😶. This doesn't happen on main. Anyone any ideas? It's not click threshold timer, as it happens even with it disabled.

fix: click threshold not working when any clickable element visible

---

src/uosc/lib/text.lua

The option did the oposite of what it was supposed to

fix: refine text_width check

---

src/uosc/main.lua

Speed < 1 can require more parts of the formatted time then when speed >= 1.
E.g. when a video is almost 1min long and the speed is reduced to <1 then the minutes part of the remaining time would still get trimmed, even though it's not `00:`.
Alternatively the max seconds could also be
```lua
local max_seconds = math.max(state.duration, (state.duration - state.time) / speed)
```
so that the time only gets longer when the remaining time is large enough to require less trimming.
Really not sure what the best way of handling this is...

fix: don't trim too much when speed < 1 with playtime-remaining

---

src/uosc/elements/Timeline.lua
src/uosc/main.lua

This sometimes increases to >0s after seeking for a split second before going back to 0s again. No idea why that happens, but the same thing also happens in stats.lua (I didn't check osc.lua).

tweak: user demuxer-cache-state/cache-duration property

---

src/uosc/elements/TopBar.lua

There is no reason why that space should be any different to the one between the playlist and the title

tweak: same spacing between all top bar elements

---

src/uosc.conf
src/uosc/elements/TopBar.lua
src/uosc/main.lua

I don't like the way left alignment looks...
The calculation of `self.ax` isn't necessary anymore with the way clicks are handled now and afaik there is no benefit in accurately adjusting the boundary box, so for the sake of simplicity I've removed that instead of making it work with left alignment.
Closes #892

feat: support aligning window controls to the left

---

src/uosc/lib/menus.lua

mpv upstream commit https://github.com/mpv-player/mpv/commit/ab3b174 has introduced support for BCP 47 language tags,
and now track lang has uppercase and lowercase content.
Avoid showing the selection status of secondary subtitle in the subtitle menu at the same time.
current behavior of mian:
apply changes:

menus.lua: tweaks and fixes the display of the track menu

---

src/uosc/elements/Timeline.lua

a7136337c852a51bf4a55da3fd69257171a40415 fixed the shown duration, but the threshold check wasn't adjusted and therefore still didn't behave the same as before 00737e1598da8756ac70f8199b022dc7cc09d43e.
3 commits for such a simple change... incredible

fix: buffered_time_threshold check

---

src/uosc.conf
src/uosc/main.lua

So far the file navigation menu would only show media files and directories, but opening playlist files via that menu is a valid use case as well.
From a quick look at `demux_playlist.c` and a bit of testing, those seem to be the only playlist formats mpv supports.
mpv can also open `.txt` files as playlists, but they need to be provided via the `--playlist=<path>` argument and thus don't work here.
ref. https://github.com/tomasklaen/uosc/discussions/926

feat: show playlist files in the file navigation menu

---

src/uosc/lib/menus.lua
src/uosc/main.lua

Opening a playlist with loadfile can lead to problems like autoload.lua populating the playlist with other files that were in the same directory as the playlist file.
To avoid that the command loadlist can be used to avoid having mpv treat the file like any other, just to notice during demuxing that it is a playlist.
ref. https://github.com/tomasklaen/uosc/pull/927#issuecomment-2210135586
@hooke007 You won't like that this is based on the file extension, but I don't know how else we would go about doing it. We could read the beginning of the file and deciding based on that, but I'd rather not do that unless it's _very_ important to do that. I've checked if we could do something via mime-type (e.g. `file --mime-type` on linux), but m3u8 playlists simply show up as plain text, so we'd have …

feat: use loadlist when opening playlists

---

src/uosc/elements/Timeline.lua

Listening to `primary_down`, but not listening to the `primary_up` event leads to that `up` event getting forwarded. Listening to `primary_click` instead avoids that problem.
Seeking chapters now happens on button up instead of button down, but that shouldn't be a problem for anyone and makes their behavior consistent with other clickable UI elements.
ref. https://github.com/tomasklaen/uosc/discussions/931

fix: use primary_click for chapter indicators

---

src/uosc.conf
src/uosc/elements/Button.lua
src/uosc/elements/Controls.lua
src/uosc/elements/ManagedButton.lua
src/uosc/lib/buttons.lua
src/uosc/lib/utils.lua
src/uosc/main.lua

Adds `set-button <name> <data_json>` message external scripts can send to add or update buttons whose state, look, and click action is defined by `data_json`.
Users can then add this button into their controls bar with `button:<name>` syntax.
Example:
```lua
mp.commandv('script-message-to', 'uosc', 'set-button', 'button-name', utils.format_json({
icon = 'icon_name',
active = true,
badge = '0',
tooltip = 'Button tooltip',
command = 'command to send on click',
}))
```
Button data interface (pseudo types):
```c
{
icon: string;
active?: boolean;
badge?: string;
command?: string | string[];
tooltip?: string;
}
```
---
closes #935

feat: `set-button` API for scripts to add custom control bar buttons

---

src/uosc/lib/char_conv.lua

When I originally added this feature, I overlooked that this was actually different from UI localization. It has different usage scenarios: UI main language and romanization files can be separated.
See-also #947

fix: always reads the romanization file for the corresponding language in the `language` option

---

README.md
src/uosc/elements/Menu.lua
src/uosc/lib/ass.lua
src/uosc/lib/menus.lua
src/uosc/lib/std.lua
src/uosc/lib/utils.lua
src/uosc/main.lua

I was implementing menu actions (item buttons), and it turned into quite a rewrite of how menu shortcuts work, and introduced a more powerful menu lifecycle API, where scripts can now get a high resolution events for various stuff, and overall get more control over menus.
I'm not _too_ happy with it, but it's the best I could come up with without breaking things.
I'm sure there are still some bugs and undesirable side effects I've failed to notice as a lot has changed.
Notable new features:
- The extended menu API is documented in the new [Menu API wiki page](https://github.com/tomasklaen/uosc/wiki/Menu-API).
- In subtitles menu, the download item has been moved to a **Load** item action.
- Playlist menu can now be sorted with big steps using ctrl+pgup/pgdwn/home/end.
- left/right arrows …

feat: menu lifecycle and actions API

---

src/uosc/elements/Timeline.lua
src/uosc/main.lua

We would end up with a playback-time way past the reported duration on some files when using `--rebase-start-time=no`, which would break the timeline display and produce seeks that were outside the playable range of the video.
Sample generated with `streamlink -o lol.ts https://www.twitch.tv/rubius 1080p50`: https://0x0.st/XwrB.ts
Before
After

fix: timeline when rebase-start-time=no

---

src/uosc/intl/zh-hans.json
src/uosc/lib/menus.lua

feat: optimize track title and update Chinese translation

---

src/uosc/lib/menus.lua

The wmic disabled by default since Win11 24H2

fix: replaces the deprecated wmic command

---

src/uosc/main.lua

with force-window=immediate and osc=yes
https://github.com/user-attachments/assets/336b83f8-3daf-48ee-ae94-661fbcd4acf3
Tested on MacOS, likely happens on other platforms too.
Because we disable the osc within the first run of the script, there are no chances for extra renders to go through.  
The previous approach was racy.
cf #736

fix: builtin osc-idlescreen flashing when mpv is launched in idle mode

---

src/uosc/elements/Menu.lua
src/uosc/lib/text.lua

This ads a working cursor when editing menu search input fields. I'd be surprised if there weren't some edge case issues I missed with all the different menu & search types we have, but as far as I can tell, at the moment there's only one small issue:
When there's a space in front of the cursor, our `text_width()` measuring misbehaves and overshoots the measurement of the width of the query tail (the part after the cursor), so the cursor position and the whole query jumps around, see below.
I've tried giving it a quick look but couldn't find an obvious fix for this. maybe @christoph-heinrich could look at it? Either way, it's still better than nothing and I wouldn't mind merging it as is.
closes #766

feat: working text cursor when editing search inputs

---

src/uosc/elements/Menu.lua
src/uosc/lib/text.lua

By the way, the `search_query_delete` function doesn't work properly.

fix: cursor in search inputs is not moved correctly by utf-8 characters

---

src/uosc/elements/Menu.lua

Pasting during an active search should paste the text into the search field, rather then execute on_paste.

fix: paste while searching

---

src/uosc/elements/Menu.lua

ass_escape() replaces leading spaces with '\h' (two characters), which led to the visible width of tail not lining up with the estimated one.
ref. https://github.com/tomasklaen/uosc/pull/1094

fix: menu search cursor position when in front of a space

---

src/uosc.conf
src/uosc/elements/Timeline.lua
src/uosc/lib/ass.lua
src/uosc/lib/utils.lua
src/uosc/main.lua

All the interactions with other options that i found are handled, so at this point this is as much done as i’m capable of.
I know the goal is to keep the config minimal, but in the end i've chosen to include the mentioned positioning for users who use a low `timeline_size` value but still want to see the heatmap. In that case, the heatmap uses the default youtube height, which coincidentally matches uosc's default timeline `40` size, so that's nice.
The `timeline_heatmap` option could still be removed, but turning it off through opacity options felt a bit convoluted.
closes #832

feat: display youtube heatmap on timeline
