- uosc.lua
Adds drawing of ab-loop time points based on chapters logic.
> AB-loop draw

- uosc.lua
> Show more information for tracks

- README.md
- uosc.lua
> Trim whitespace from context menu and allow empty folders

- uosc.lua
The playlist menu list would reflect changes of the underlying data.
That now also happens for the menu lists of all three tracks as well as
chapters. Closes #21
> Update subtitle, audio, video and chapter menu lists

- uosc.lua
The first byte of character greater than or equal to `1100 0000` will be estimated as double width.
https://en.wikipedia.org/wiki/UTF-8#Encoding
[Advance measure](https://developer.mozilla.org/en-US/docs/Glossary/advance_measure) is a better way to do this. But for now, this is good enough.
> Better text_width_estimate

- uosc.lua
> Fix accessing member of nil value.

- uosc.lua
Prepends playlist position to the display title in the top left corner, if the playlist has more than one item.
> Display playlist position

- uosc.lua
Let's bring a better experience to Windows users!
It works on Windows Vista and later.
PS: I'm not a lua programmer, so the code might be a little bad.
> File picker support for navigating to other drives on Windows

- uosc.lua
Menu dimensions used to not be updated when changing dimensions, resulting in the wrong size when e.g. entering fullscreen while the menu is open.
Now the dimensions are always updated on display change, but the width estimation still only runs on initialization and when entering/exiting fullscreen/maximized.
I didn't test it, but I think I might have broken this with #116.
> Correctly update menu dimensions

- scripts/uosc.lua
This was originally intended for the other PR, but I had to quickly do something before committing/pushing and by the time I got back it was already merged, so another PR it is. Wasn't sure if you would approve of that change anyway, so it's probably better to be separate.
> refactor: move chapter range handling into loop and break early

- scripts/uosc.lua
This is simply the fix I posted in #192. Seems to work pretty well so far.
Really good hidpi support would need more invasive changes, but this is good enough for now.
Closes #192
> fix: mouse input with fractional scaling

- scripts/uosc.lua
As mentioned [here](https://github.com/tomasklaen/uosc/issues/177#issuecomment-1247147261) it currently does not react to changes in the title property.
> fix: react to changes in the `title` property

- scripts/uosc.lua
> Fix tooltips for built-in controls

- scripts/uosc.lua
Most of that was already written when you closed the other PR, so I thought not offering it was a bit of a waste.
The first commit mostly came to be because I found it odd that parsing chapters would need the duration. Ended up as a general improvement to chapter procurement. `normalize_chapters()` doesn't really need to return the table, but I left it as it was in case the implementation changes at some point.
The second commit now has the `options.chapter_ranges` replaced with a table of the parsed chapter ranges.
`state.chapter_ranges` now only contains the ranges that have been matched to the current chapters, not the whole definition + matches.
The serialization function has been factored out into a standalone function, instead of storing new function in each `options.chapter_range`. …
> Chapter stuff

- scripts/uosc.lua
The timeline should show to be uncached as soon as can.
Not sure if the callback is really necessary. In my testing the `demuxer-via-network` observer always gets called once at the beginning of the file right before the `demuxer-cache-state` observer and right after the `duration` observer, so it shouldn't really make a difference. But I don't think that's guaranteed, so I've added the callback just in case.
The state already had a `is_stream` variable that wasn't used.
> fix: show fully uncached range for network streams

- scripts/uosc.lua
> fix: show cache indication whenever cache is available

- scripts/uosc.lua
This still shows uncached ranges as early as we can, but is more reliable.
This shouldn't produce any false positives anymore and also get rid of uncached ranges when there is no caching.
---
This removes the `cache-buffering-state`, but we could use that to display some buffering symbol/animation as is shown in web browsers. Don't know if that's even desirable, but if you ever want to do this, it would basically be `if value < 100 then show_buffering() else hide_buffering() end`.
> fix: showing uncached ranges when not caching

- scripts/uosc.lua
The resolution passed to ass was not necessarily an integer while scaling, and I think that's what's caused the issues noted in #238. In my testing the thumbnail decoration renders nicely now with all sorts of fractional scaling factors.
@hooke007 Can you please test if this resolves your issues?
> fix: integer resolution when scaling

- scripts/uosc.lua
Managed to get a nil error there, but it happens rarely.
> fix: possible nil error in uncached ranges generation

- scripts/uosc.lua
ref https://github.com/tomasklaen/uosc/discussions/261#discussioncomment-3724877
> feat: draw chapter indicators of chapter ranges

- scripts/uosc.lua
> fix: show default menu when input.conf doesn't exist

- scripts/uosc.lua
The math is much simpler then it used to be and there are some more simplifications I can do, but that will have to wait until tomorrow.
Mouse input works correctly but the code is horrible. Again, tomorrow.
I don't really like how the progress bar behaves when seeking, but this is technically correct behavior.
> fix: new progress indicator line behavior

- README.md
- script-opts/uosc.conf
- scripts/uosc.lua
Todo:
~I have no idea how to add a new control. Can anybody help me?~
Close https://github.com/tomasklaen/uosc/issues/20
> feat: add `editions` menu,`editions` control and  `has_many_editon` disposition

- scripts/uosc.lua
close https://github.com/tomasklaen/uosc/issues/285
> fix: `osd-align-*` properties messing up the UI

- scripts/uosc.lua
This is merely a proof of concept. I've been wondering how it would look ever since #252.
Didn't know what texture to use, so I simply took the the same as in the timeline and volume slider.
Any ideas on how it should look are welcome.
> feat: add buffering indicator

- scripts/uosc.lua
> fix: use mouse-pos property instead of keybinds

- script-opts/uosc.conf
- scripts/uosc.lua
ref. https://github.com/tomasklaen/uosc/discussions/300#discussioncomment-3818107
> feat: automatically choose between fast and exact seeking

- scripts/uosc.lua
Get the properties relevant to the title, observe and update based on their changes.
> fix: properly update title

- scripts/uosc.lua
> fix: use `ass_safe_title`

- scripts/uosc.lua
This gives us a little bit more leeway to prevent clipping from inaccurate width estimation.
ref. https://github.com/tomasklaen/uosc/pull/321#issuecomment-1278600099
> fix: spacing and clipping in menu

- scripts/uosc.lua
With this touchscreen support is pretty decent, and while it is very much a WIP, it already works pretty well.
Supporting scrolling by dragging necessitates that menu item selection now happens on mouse up rather then mouse down, but that is how applications usually behave anyway.
I don't like how many variables it introduces, especially all the `*_last_x` ones, but updates come in such irregular intervals that it requires some filtering to get good results. Sometimes there isn't even a milliseconds between position updates, and other times it's >30ms, which then leads to huge variance in calculated velocities. Maybe the updates would be more reliable if we switch to `mouse_move` while the cursor is over elements.
Also the math for scroll position updates via momentum is not great. It …
> feat: drag to scroll for menu

- scripts/uosc.lua
- scripts/uosc_shared/lib/text.lua
- scripts/uosc_shared/lib/utils.lua
> Fix osd resolution

- scripts/uosc_shared/lib/text.lua
Moved the declaration above it's usage as noted in https://github.com/tomasklaen/uosc/pull/393#issuecomment-1356759785
This did improve width estimation for me in some situations where I thought that's just some inaccuracy from estimating it with individual characters, but after this change its better now. Based on that I'd expect it to also improve https://github.com/tomasklaen/uosc/issues/354#issuecomment-1336351521.
I've checked all other variables in the file and they are all fine.
> fix: declare variable before function using it

- script-opts/uosc.conf
- scripts/uosc.lua
- scripts/uosc_shared/lib/utils.lua
ref: https://github.com/tomasklaen/uosc/issues/390
> feat: add option to delete file to Recycle Bin

- README.md
- script-opts/uosc.conf
I am very happy to see how new activity this project has gotten over the last year. Thanks to everyone!
While reading the documentation I noticed some minor parts require updating and I added some small fixes for typos, grammar and clarity while I was at it.
I added a small section with terminal commands for quickly installing or updating uosc's latest release on Linux or Mac. I also added a missing Readme section about the shuffle command.
> docs: minor additions and cleanup

- scripts/uosc.lua
> fix: infinite margin on initialization

- scripts/uosc.lua
ref. https://github.com/tomasklaen/uosc/commit/6d58ef4c9986b6b38ad60551a891f7d690b6c1a5#commitcomment-109122443
> tweak: elements with min_visibility > 0.5 cause a margin

- scripts/uosc.lua
> fix: translate built-in menu titles

- README.md
Hi,
just added equivalent commands for windows to install the project.
Let me know if it's ok.
Regards
> doc: add windows commands

- scripts/uosc/elements/Menu.lua
I think this should be enough. Can you guys still reproduce? @dyphire @christoph-heinrich
closes #610
> fix: stale (closed) menus triggering cursor events

- scripts/uosc/elements/Menu.lua
As soon as it encounters the first real world use case it falls apart :laughing: https://github.com/po5/memo/pull/19
Wouldn't have even noticed those if everything went smoothly on the memo side...
> fix: external search in menu

- scripts/uosc/elements/Controls.lua
- scripts/uosc/elements/Timeline.lua
- scripts/uosc/elements/TopBar.lua
- scripts/uosc/elements/Volume.lua
- scripts/uosc/elements/WindowBorder.lua
- scripts/uosc/main.lua
mpv has added a new option to control window title bar state, which requires relevant adjustments to be added in uosc.
Ref https://github.com/mpv-player/mpv/commit/ee24dd04194aadfda882fd73553cba8d1e734567
> fix: adapt to the new title bar state of mpv

- scripts/uosc/elements/Menu.lua
- scripts/uosc/lib/text.lua
I didn't like the name from the very beginning, but I couldn't think of something better. Ever since I realized that such characters are called "initials", this name bothered me every time I saw it.
> refactor: rename first_word_chars() to initials()

- scripts/uosc/elements/Menu.lua
- scripts/uosc/lib/std.lua
@christoph-heinrich did I break something? :)
> fix: search not selecting 1st item in results

- scripts/uosc/elements/Menu.lua
> fix: menu positioning issues

- scripts/uosc/elements/Menu.lua
Tested with #654 and will require a rebase after that's merged.
> fix: clipping of menu title and search

- scripts/uosc/elements/Element.lua
- scripts/uosc/elements/Menu.lua
- scripts/uosc/elements/Timeline.lua
- scripts/uosc/elements/Volume.lua
- scripts/uosc/lib/text.lua
- scripts/uosc/lib/utils.lua
- scripts/uosc/main.lua
Apparently [math.huge](https://www.lua.org/manual/5.1/manual.html#pdf-math.huge) exists, so we might as well use it.
> refactor: use math.huge

- scripts/uosc/elements/Timeline.lua
- scripts/uosc/elements/Volume.lua
- scripts/uosc/lib/ass.lua
ref. https://github.com/tomasklaen/uosc/pull/699#issuecomment-1763430615
> feat: add transparent full volume icon

- dist/scripts/uosc/elements/Volume.lua
ref. https://github.com/tomasklaen/uosc/issues/722#issuecomment-1783866244
> fix: allow a volume border of 0

- src/uosc/lib/cursor.lua
> refactor: remove check before adding 0.5 to cursor position

- src/uosc/lib/menus.lua
mpv.net v7 returns the whole input.conf content instead of the path for the `input-conf` property.
ref. https://github.com/mpvnet-player/mpv.net/issues/572#issuecomment-1793775980
> fix: menu config with mpv.net

- src/uosc/elements/Timeline.lua
fixes 00737e1598da8756ac70f8199b022dc7cc09d43e
> fix: scale cache duration with speed again

- src/uosc/elements/Menu.lua
- src/uosc/main.lua
See-Also: https://github.com/mpv-player/mpv/pull/15832
> feat: adapting ime features for mpv

- src/uosc/elements/Menu.lua
Fix 7de82c3
Presented by there: https://github.com/Tony15246/uosc_danmaku/issues/172
> fix: incorrect setting of IME
